Services/AnimalRecognition.Web/Controllers/RecognitionController.cs
using AnimalRecognition.Web.Models.RecognitionModels;
using AnimalRecognition.Common;
using AnimalRecognition.Detect;
using Microsoft.AspNetCore.Mvc;
using AnimalRecognition.Web.Dto.Request.Base;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using AnimalRecognition.Web.Dto.Request;

namespace AnimalRecognition.Web.Controllers
{
    public class RecognitionController : Controller
    {
        private readonly ImageRecognition _recognition;

        public RecognitionController(ImageRecognition recognition) => _recognition = recognition;

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<RequestRecognitionResult> RecognitionImage(RecognitionImageViewModel model)
        {
            if (ModelState.IsValid)
            {
                byte[] image = await Helper.ConvertIFormFileToByteArrayAsync(model.Image).ConfigureAwait(false);

                var result = await _recognition.Recognition(image).ConfigureAwait(false);

                return result.Percent > 0.7 ? 
                    new RequestRecognitionResult(true, result.Entity, result.Percent) : 
                    new RequestRecognitionResult(true, "Unknown", 0);
            }

            var errors = ModelState.Where(x => x.Value.ValidationState == ModelValidationState.Invalid).Select(x =>
                new ModelStateError(x.Key, x.Value.Errors.Count > 0 ? x.Value.Errors[0].ErrorMessage : string.Empty)
            );

            return new RequestRecognitionResult(false, errors);
        }
    }
}

Services/AnimalRecognition.Web/Views/Shared/ModalWindow/_ModalWindowClose.cshtml
<div class="modal_window_close">
    <div class="close_circle">
        <svg width="12" height="12" viewBox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M11 1L1 11" stroke="#FFFEF6" stroke-width="2" stroke-miterlimit="10"
                  stroke-linecap="round"></path>
            <path d="M11 11L1 1" stroke="#FFFEF6" stroke-width="2" stroke-miterlimit="10"
                  stroke-linecap="round"></path>
        </svg>
    </div>
</div>

Services/AnimalRecognition.Web/Views/Shared/ModalWindow/_ModalWindowLogIn.cshtml
@model LogInViewModel

<section id="modal_window_login" class="blackout">
    <div class="modal_window">
        <div class="modal_window_container">
            <form id="form_login" class="form" method="post" asp-controller="Account" asp-action="LogIn">
                @Html.AntiForgeryToken()
                <h1 class="form_title">Log in</h1>
                <div class="form_group">
                    <input asp-for="Email" class="form_input" placeholder=" ">
                    <label asp-for="Email" class="form_label"></label>
                    <span asp-validation-for="Email" class="form_error"></span>
                </div>
                <div class="form_group form_group_last">
                    <input asp-for="Password" class="form_input" placeholder=" ">
                    <label asp-for="Password" class="form_label"></label>
                    <span asp-validation-for="Password" class="form_error"></span>
                </div>
                <div class="form_group_send">
                    <span class="form_global_error"></span>
                    <input type="submit" class="form_button" value="Log In" />
                </div>

                <partial name="Components/_ModalWindowComponentLoading.cshtml" />
            </form>

            <partial name="Components/_ModalWindowComponentClose.cshtml" />
        </div>
    </div>
</section>

Services/AnimalRecognition.Web/Views/Shared/ModalWindow/_ModalWindowPrivacy.cshtml
<section id="modal_window_privacy" class="blackout">
    <div class="modal_window">
        <div class="modal_window_container">
            <center>
                <h1 class="form_title">Privacy</h1>
            </center>
            <div class="content_privacy">
                <p>This project is designed to evaluate code quality.</p>
                <br />
                <p>I have not implemented features such as password recovery, user role distribution, and so on.</p>
                <br />
                <p>As I mentioned before, the project is created for code evaluation and can be improved infinitely.</p>
                <br />
                <p>After registering and verifying your account, you can use a neural network that classifies animals.</p>
                <br />
                <p>Here are all the entities it can recognize:</p>
                <br />
                <p>Ant, Bat, Bee, Bird, Butterfly, Cat, Chicken, Crab, Dog, Dragonfly, Duck, Elephant, Fish, Fox, Giraffe, Hedgehog, Horse, Hummingbird, Jellyfish, Ladybug, Lion,
                    Octopus, Parrot, Penguin, Rabbit, Shark, Squirrel, Starfish, Turtle.
                </p>
                <br />
                <br />
                <p>Source: <a href="https://github.com/N-Fumbo/DetectorAnimal" class="link" target="_blank">GitHub</a></p>
            </div>
            <partial name="Components/_ModalWindowComponentClose.cshtml" />
        </div>
    </div>
</section>

Services/AnimalRecognition.Web/Views/Shared/ModalWindow/_ModalWindowRecognition.cshtml
@model RecognitionImageViewModel

<section id="modal_window_recognition" class="blackout">
    <div class="modal_window">
        <div class="modal_window_container">
            @if (User.Identity.IsAuthenticated)
            {
                <form id="form_recognition" class="form" asp-controller="Recognition" asp-action="RecognitionImage">
                    @Html.AntiForgeryToken()
                    <h1 class="form_title">Identify</h1>

                    <img id="image_preview" class="image_input" src="~/images/image_input.png" alt="input image" />

                    <input asp-for="Image" id="image_input" type="file" accept=".jpg,.jpeg,.png">

                    <div class="form_group_send">
                        <span class="form_global_error"></span>
                        <span id="recognition_result"></span>
                        <input type="submit" class="form_button" value="Send" />
                    </div>

                    <partial name="Components/_ModalWindowComponentLoading.cshtml" />
                </form>
            }
            else
            {
                <center>
                    <h2>Account required.</h2>
                    <br>
                </center>
            }
            <partial name="Components/_ModalWindowComponentClose.cshtml" />
        </div>
    </div>
</section>

Services/AnimalRecognition.Web/Views/Shared/ModalWindow/_ModalWindowRegister.cshtml
@model RegisterViewModel

<section id="modal_window_register" class="blackout">
    <div class="modal_window">
        <div class="modal_window_container">
            <form id="form_register" class="form" method="post" asp-controller="Account" asp-action="Register" enctype="multipart/form-data">
                @Html.AntiForgeryToken()
                <h1 class="form_title">Register</h1>
                <div class="form_group">
                    <input asp-for="Name" class="form_input" placeholder=" ">
                    <label asp-for="Name" class="form_label"></label>
                    <span asp-validation-for="Name" class="form_error"></span>
                </div>
                <div class="form_group">
                    <input asp-for="Email" class="form_input" placeholder=" ">
                    <label asp-for="Email" class="form_label"></label>
                    <span asp-validation-for="Email" class="form_error"></span>
                </div>
                <div class="form_group">
                    <input asp-for="Password" class="form_input" placeholder=" ">
                    <label asp-for="Password" class="form_label"></label>
                    <span asp-validation-for="Password" class="form_error"></span>
                </div>
                <div class="form_group form_group_last">
                    <input asp-for="PasswordConfirmed" class="form_input" placeholder=" ">
                    <label asp-for="PasswordConfirmed" class="form_label"></label>
                    <span asp-validation-for="PasswordConfirmed" class="form_error"></span>
                </div>
                <div class="form_group_send">
                    <span class="form_global_error"></span>
                    <input type="submit" class="form_button" value="Create" />
                </div>
                <partial name="Components/_ModalWindowComponentLoading.cshtml" />
            </form>

            <partial name="Components/_ModalWindowComponentClose.cshtml" />
        </div>
    </div>
</section>